name: Test

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7, 3.0]
        thor: [1.0.1, 1.1.0]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler
      - run: echo "gem 'thor', '${{ matrix.thor }}'" >> Gemfile
      - run: bundle install
      - run: bundle exec itamae
